### ISSUE TITLE
Add support for URL Input + 2 level sitemaps

### ISSUE THREAD

**Issue by alexgarciab** [tcaldron/xmlscrape#2]
Hi there, I have been testing the script and it works OK, but I miss two important features:

1) Have the ability to pass a XML URL via parameter, so that the scripts, pulls the XML file directly from a URL instead of from the local folder.

2) Have the ability to extract URLs from 2 level sitemaps. In Wordpress, it is pretty common to have 2 level sitemaps, meaning, a sitemap within a sitemap. Right now, it just crawls the first level.

Would you be willing to add these 2 features? It will make the script much more complete.

**Comment by tcaldron** [comment]
These seem like good features to have. I’ve run into the WordPress Sitemap
index thing a lot myself. I’ll start working on these soon.
